name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        # python 3.12 is default version of Ubuntu 24.04 LTS
        python-version: ["3.12", "3.13"]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
      -
        name: Analyze the code
        run: |
          poetry run isort --check-only .
          poetry run black --check .
          poetry run flake8 .
          poetry run mypy .
      -
        name: Run Tests
        run: poetry run pytest
